# Generated by Django 5.1.3 on 2025-05-09 09:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ideas', '0004_post_upvote_count_upvote'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='post',
            name='upvote_count',
        ),
    ]
